<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
use Drupal\Core\Form\FormStateInterface;

function axelerant_test_form_alter(&$form, FormStateInterface $form_state, $form_id) {
    $config = \Drupal::configFactory()->getEditable('system.site');
  if($form_id == "system_site_information_settings"){
      
          $form['siteapikey'] = [
      '#type' => 'textfield',
      '#title' => t('Site API Key'),
              
      '#placeholder' => t('No API Key yet'),
      '#default_value' =>$config->get('siteapikey')?$config->get('siteapikey'):'',       
    ];
          if($config->get('siteapikey')){
          $form['actions']['submit']['#value'] = t('Update configuration') ;
          }
          
  $form['#submit'] = array_merge(['set_api_value'], $form['#submit']);
  }
}

function set_api_value(array &$form, FormStateInterface $form_state) {
  $siteapikey = $form_state->getValue('siteapikey');
 $conf =  \Drupal::configFactory()->getEditable('system.site')->set('siteapikey', $siteapikey);
 if($siteapikey)
 \Drupal::messenger()->addMessage(t("Site API Key has been saved with $siteapikey."), 'status');
}